### ISSUE TITLE
Is there a way to make the dropdown work on ipad

### ISSUE THREAD

**Issue by sufguts** [n33/jquery.dropotron#10]
Using a responsive template with skel.js, and the ipad is, I guess, such high resolution that it shows desktop mode, not the narrower mobile mode. The trigger link (which shows the dropdown when you mouseover) just acts as a regular link, so the dropdown doesn't show up.

I see the Expansion Mode can be hover or click - is there a way to say "if it's a touch screen use click, and if it's a mouse use hover"?

**Comment by sufguts** [comment]
figured it out. under $opener, changed .on('click touchend', to .on('click touchstart', and it seems to work

**Comment by n33** [comment]
:+1:

**Comment by Bendico** [comment]
I'm using a similar template and still have problems with the dropotron on the iPad. After applying sufguts' fix, the drop menus display on the iPad, but then the links don't work. Nothing else happens when you tap the menu items. An iPad user would probably expect the menu item link to redirect on the second tap, if there is a drop menu also associated with the item. I've been trying to figure out how to do it in the dropotron.js, but unfortunately, I'm not a JavaScript wiz. Anyone?
